import pytest
from unittest.mock import patch, AsyncMock
from main import app
from nova_event_bus.exceptions import EventBusConnectionError
from plugins.base import Plugin
from core.models import PluginContext, PluginResult

class MockSuccessPlugin(Plugin):
    @property
    def name(self) -> str:
        return "MockSuccessPlugin"
    @property
    def description(self) -> str:
        return "Mock Success"
    @property
    def id(self) -> str:
        return "mock_success"
    async def execute(self, context: PluginContext) -> PluginResult:
        return PluginResult(success=True, speech="Success Speech")

@pytest.mark.asyncio
async def test_happy_path_event_publishing(client):
    # Register the mock plugin in the app state plugin manager
    app.state.plugin_manager.plugins["MockSuccessPlugin"] = MockSuccessPlugin()
    
    with patch("nova_event_bus.NatsEventBus.publish", new_callable=AsyncMock) as mock_publish:
        plan_data = {
            "steps": [
                {
                    "plugin": "MockSuccessPlugin",
                    "confidence": 0.95,
                    "parameters": {},
                    "channel": "voice",
                    "context": {
                        "raw_text": "test query",
                        "normalized_text": "test query",
                        "correlation_id": "test-correlation-123",
                        "channel": "voice",
                        "metadata": {"test_key": "test_val"}
                    },
                    "security": {}
                }
            ]
        }
        
        response = client.post("/api/v1/execute-plan", json=plan_data)
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        
        # Verify that publish was called once
        mock_publish.assert_called_once()
        published_event = mock_publish.call_args[0][0]
        
        # Verify fields of the published event
        assert published_event.response == "Success Speech"
        assert published_event.plugin == "MockSuccessPlugin"
        assert published_event.confidence == 0.95
        assert published_event.correlation_id == "test-correlation-123"
        assert published_event.channel == "voice"
        assert published_event.metadata == {"test_key": "test_val"}
        assert published_event.execution_time_ms == data["execution_time_ms"]

@pytest.mark.asyncio
async def test_event_publishing_nats_failure(client):
    app.state.plugin_manager.plugins["MockSuccessPlugin"] = MockSuccessPlugin()
    
    with patch("nova_event_bus.NatsEventBus.publish", new_callable=AsyncMock) as mock_publish:
        mock_publish.side_effect = EventBusConnectionError("Connection lost")
        
        plan_data = {
            "steps": [
                {
                    "plugin": "MockSuccessPlugin",
                    "confidence": 0.95,
                    "parameters": {},
                    "channel": "voice",
                    "context": {
                        "raw_text": "test query",
                        "normalized_text": "test query",
                        "correlation_id": "test-correlation-123",
                        "channel": "voice",
                        "metadata": {}
                    },
                    "security": {}
                }
            ]
        }
        
        # Request should succeed (HTTP 200) despite event bus failure
        response = client.post("/api/v1/execute-plan", json=plan_data)
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        mock_publish.assert_called_once()

@pytest.mark.asyncio
async def test_retrocompatibility_missing_correlation_id_and_channel(client):
    with patch("nova_event_bus.NatsEventBus.publish", new_callable=AsyncMock) as mock_publish:
        # Request to /api/v1/resolve omitting correlation_id and channel
        req_data = {
            "text": "hola"
        }
        response = client.post("/api/v1/resolve", json=req_data)
        assert response.status_code == 200
        plan = response.json()
        
        # Validate that correlation_id and channel were autogenerated/populated
        step = plan["steps"][0]
        correlation_id = step["context"]["correlation_id"]
        channel = step["context"]["channel"]
        assert correlation_id is not None
        assert len(correlation_id) > 0
        assert channel == "voice"
        
        # Execute the plan
        exec_response = client.post("/api/v1/execute-plan", json=plan)
        assert exec_response.status_code == 200
        exec_data = exec_response.json()
        assert exec_data["success"] is True
        
        # Verify event was published with the autogenerated correlation_id and default channel
        mock_publish.assert_called_once()
        published_event = mock_publish.call_args[0][0]
        assert published_event.correlation_id == correlation_id
        assert published_event.channel == "voice"

@pytest.mark.asyncio
async def test_response_generated_event_serialization_integration(client):
    app.state.plugin_manager.plugins["MockSuccessPlugin"] = MockSuccessPlugin()
    
    # We patch NatsClient inside nova_event_bus.client, so the actual publish runs
    with patch("nova_event_bus.client.NatsClient") as MockNatsClient:
        mock_client_instance = MockNatsClient.return_value
        mock_client_instance.is_connected = True
        mock_client_instance.publish = AsyncMock()
        
        # Override the app event bus client to use a new NatsEventBus which will use our MockNatsClient
        from nova_event_bus import NatsEventBus
        real_bus = NatsEventBus()
        # We need to call connect so it initializes NatsClient
        await real_bus.connect()
        
        # Backup original executor's event bus
        original_bus = app.state.executor.event_bus
        app.state.executor.event_bus = real_bus
        
        try:
            plan_data = {
                "steps": [
                    {
                        "plugin": "MockSuccessPlugin",
                        "confidence": 0.95,
                        "parameters": {},
                        "channel": "voice",
                        "context": {
                            "raw_text": "test query",
                            "normalized_text": "test query",
                            "correlation_id": "test-correlation-123",
                            "channel": "voice",
                            "metadata": {"test_key": "test_val"}
                        },
                        "security": {}
                    }
                ]
            }
            
            response = client.post("/api/v1/execute-plan", json=plan_data)
            assert response.status_code == 200
            data = response.json()
            assert data["success"] is True
            
            # Verify the mock NatsClient.publish was called with serialized payload
            mock_client_instance.publish.assert_called_once()
            args, kwargs = mock_client_instance.publish.call_args
            subject = args[0]
            serialized_payload = args[1]
            
            assert subject == "orchestrator.response.generated"
            import json
            payload_data = json.loads(serialized_payload.decode("utf-8"))
            assert payload_data["type"] == "ResponseGeneratedEvent"
            assert payload_data["payload"]["response"] == "Success Speech"
            assert payload_data["payload"]["plugin"] == "MockSuccessPlugin"
            assert payload_data["payload"]["confidence"] == 0.95
            assert "timestamp" in payload_data["payload"]
            # Verify it is serialized to ISO string
            assert isinstance(payload_data["payload"]["timestamp"], str)
            assert payload_data["payload"]["correlation_id"] == "test-correlation-123"
            assert payload_data["payload"]["channel"] == "voice"
            assert payload_data["payload"]["metadata"] == {"test_key": "test_val"}
            
        finally:
            # Restore
            app.state.executor.event_bus = original_bus

